### ISSUE TITLE
This README.md is very simple,or not?

### ISSUE THREAD

**Issue by Asunqingwen** [ZviBaratz/django_dicom#5]
I use your code in my django project,not work,have some proble like this:
ERRORS:
django_dicom.NIfTI.path: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.
django_dicom.Patient.subject: (fields.E300) Field defines a relation with model 'research.Subject', which is either not installed, or is abstract.
django_dicom.Patient.subject: (fields.E307) The field django_dicom.Patient.subject was declared with a lazy reference to 'research.subject', but app 'research' isn't installed.

Is the version of django?
my django version is 2.1.7
hope you reply soon
thank you!

**Comment by sivang** [comment]
> I use your code in my django project,not work,have some proble like this:
> ERRORS:
> django_dicom.NIfTI.path: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.
> django_dicom.Patient.subject: (fields.E300) Field defines a relation with model 'research.Subject', which is either not installed, or is abstract.
> django_dicom.Patient.subject: (fields.E307) The field django_dicom.Patient.subject was declared with a lazy reference to 'research.subject', but app 'research' isn't installed.
> 
> Is the version of django?
> my django version is 2.1.7
> hope you reply soon
> thank you!

Thank you for your feedback! Can you try and use postgresql instead?
Also, it seems you're using a version of a WIP code, and we're working on fixing this, as we're moving from using django templates to a headless architecture (so it'd be a VueJS frontend and django rest framework backend).

Could you please provide your exact steps to install and reproduce the issue so even though, we may try to help? :)
